*filter
:ufw-http - [0:0]
:ufw-http-logdrop - [0:0]
### RULES ###

### Start HTTP ###

# Allow ping.
-A INPUT -p icmp -m state --state NEW --icmp-type 8 -j ACCEPT

# Enter rule
-A ufw-before-input -p tcp --dport '{{http_port}}'   -j ufw-http
-A ufw-before-input -p tcp --dport '{{https_port}}'  -j ufw-http

# Limit connections per IP
-A ufw-http -m state --state NEW -m recent --name conn_per_ip --set
-A ufw-http -m state --state NEW -m recent --name conn_per_ip --update --seconds 10 --hitcount 20 -j ufw-http-logdrop

# Limit packets per IP
-A ufw-http -m recent --name pack_per_ip --set
-A ufw-http -m recent --name pack_per_ip --update --seconds 1  --hitcount 20  -j ufw-http-logdrop

# Accept
-A ufw-http -j ACCEPT

### End HTTP ###
