---
# tasks file for monitoring
# Installation of monitoring tools

  - name: Install monitoring tools
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - logwatch
      - chkrootkit
      - nmap
      - net-tools

# Configure Logwatch 

  - name: Configure Logwatch
    replace:
      name: /usr/share/logwatch/default.conf/logwatch.conf
      regexp: 'MailTo = root'
      replace: 'MailTo = "{{ Email }}"'

  - name: Configure Logwatch
    replace:
      name: /usr/share/logwatch/default.conf/logwatch.conf
      regexp: 'Detail = Low'
      replace: 'Detail = Medium'

  - name: Configure Logwatch
    replace:
      name: /usr/share/logwatch/default.conf/logwatch.conf
      regexp: 'Range = yesterday'
      replace: 'Range = Today'

# Create a directory for chkrootkit
  
  - file: 
      path: /etc/chkrootkit 
      state: directory
      mode: 0755 

# Update chkrootkit configuration
 
  - name: Update chkrootkit config
    template:
      src: chkrootkit.conf.j2 
      dest: /etc/chkrootkit/chkrootkit.conf
      owner: root
      group: root
      mode: 0644

# Search for open ports with nmap

  - name: Scan for open ports
    command: nmap -v -sT '{{ IP }}'
    register: results

  - name: Get results from nmap
    debug:
      var: results

  - name: SYN scanning
    command: nmap -v -sS '{{ IP }}'
    register: results

  - name: Get results from nmap
    debug:
      var: results

# Use netstat to view open services

  - name: Open processes using netstat
    shell: netstat -tunlp
    register: results

  - name: Get results from netstat
    debug: 
      var: results



      
    
