---
# tasks file for monitoring
# Installation of monitoring tools

  - name: Install monitoring tools
    apt:
      name: chkrootkit
      state: present
    with_items:
      - logwatch
      - chkrootkit
      - nmap
      - net-tools

# Configure Logwatch 

  - name: Configure Logwatch
    command: logwatch --detail Medium --mailto {{ Email }} --output mail --service All --range 'between -7 days and today'  
     
# Create a directory for chkrootkit
  
  - file: 
      path: /etc/chkrootkit 
      state: directory
      mode: 0755 

# Update chkrootkit configuration
 
  - name: Update chkrootkit config
    template:
      src: chkrootkit.conf.j2 
      dest: /etc/chkrootkit/chkrootkit.conf
      owner: root
      group: root
      mode: 0644

# Run Chkrootkit

  - name: Run chkrootkit
    shell: chkrootkit
    register: results

  - name: Get results from chkrootkit
    debug:
      var: results

# Search for open ports with nmap

  - name: Scan for open ports
    command: nmap -v -sT '{{ IP }}'
    register: results

  - name: Get results from nmap
    debug:
      var: results

  - name: SYN scanning
    command: nmap -v -sS '{{ IP }}'
    register: results

  - name: Get results from nmap
    debug:
      var: results

# Use netstat to view open services

  - name: Open processes using netstat
    shell: netstat -tunlp
    register: results

  - name: Get results from netstat
    debug: 
      var: results




