---
# tasks file for Setup

  - name: Install pip from apt
    apt: 
      name: python-pip
      state: present

  - name: Update APT package cache
    apt: 
      update_cache: yes

  - name: Run apt-get upgrade
    apt: 
      upgrade: full

# Set username and password

  - user:
      name: "{{ user }}"
      password: "{{ password }}"
      state: present

# Use netstat to view open services
 
  - name: Install netstat from apt
    apt: 
      name: net-tools 
      state: present

  - name: Open processes using netstat
    shell: netstat -tunlp
    register: results

  - name: Get results from netstat
    debug: 
      var: results

# Disable IPv6 using sysctl

  - name: Disable IPv6
    sysctl: 
      name: "{{ item }}" 
      value: 1
      state: present
    with_items:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6
      - net.ipv6.conf.lo.disable_ipv6

# Secure Shared Memory 

  - name: Secure Sared Memory 
    lineinfile:
      dest: /etc/fstab
      line: 'tmpfs /run/shm tmpfs defaults,noexec,nosuid 0 0'
      state: present

# Mount fstab

  - name: Mount fstab
    mount:
      name: /etc/fstab
      state: present

# SSH keys for each user

  - authorized_key: 
      user: node-1
      key: "{{ lookup('file', './setup/files/ssh_keys/node-1.pub') }}"
 
  - authorized_key: 
      user: node-2
      key: "{{ lookup('file', './setup/files/ssh_keys/node-2.pub') }}"

  - authorized_key: 
      user: node-3
      key: "{{ lookup('file', './setup/files/ssh_keys/node-3.pub') }}"

  - authorized_key: 
      user: node-4
      key: "{{ lookup('file', './setup/files/ssh_keys/node-4.pub') }}"


