---
# tasks file for Setup

  - name: Install pip from apt
    apt: 
    name: python-pip
    state: present

  - name: Update APT package cache
    apt: 
    update_cache: yes

  - name: Run apt-get upgrade
    apt: 
    upgrade: full

  - name: Username and Password
      user: user
      password: "{{password}}"

# Use netstat to view open services
 
  - name: Install netstat from apt
    apt: 
    name: net-tools 
    state: present

  - name: Open processes using netstat
    shell: netstat -tunlp
    register: results

  - name: Get results from netstat
    debug: 
    var: results

# Disable IPv6 using sysctl

  - name: Disable IPv6
    sysctl: 
    name: {{ item }} 
    value: 1
    state: present
    with_items:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6
      - net.ipv6.conf.lo.disable_ipv6

# Secure Shared Memory 

  -name: Secure Sared Memory 
   lineinfile:
   dest: /etc/fstab
   line: 'tmpfs /run/shm tmpfs defaults,noexec,nosuid 0 0'
   state: present

# Mount fstab

  -name: Mount fstab
   mount:
   name: /etc/fstab
   state: present

