---
# tasks file for intrusion

  - name: Installing IntrusionDetection-psad 
    apt:
      pkg: psad
      state: present

# Configure psad
   
  - name: Configure psad
    template:
      src: psad.conf
      dest: /etc/psad/psad.conf
    notify: 
      - restart psad
